### ISSUE TITLE
Allow to pass a set of rules to ignore

### ISSUE THREAD

**Issue by dokempf** [lukasmartinelli/hadolint#40] opened 2016-08-10 11:17 UTC
It would be nice if it would be possible to pass a set of rules that should be ignored by the linter. Compare to python, where pep8 is an accepted standard, but almost every project defines 2-3 well-thought-of exceptions. I cannot simply ignore the output, as I want to use hadolint in a CI system.

FWIW, the rule that I disagree with is DL3008.

**Comment by ye** [comment] 2016-08-17 20:37
This is a duplicate of #24

**Closed** 2016-08-18 08:20 UTC
Labels: duplicate
