### ISSUE TITLE
MAINTAINER DEPRECATED in docker 1.13

### ISSUE THREAD

**Issue by xinity** [lukasmartinelli/hadolint#77] opened 2017-02-08 13:51 UTC
MAINTAINER is deprecated and replaced by LABEL in docker 1.13+

could be a good idea to update hadolint :)

**Comment by backus** [comment] 2017-02-08 19:31
I think this is a dupe of https://github.com/lukasmartinelli/hadolint/issues/71. Closing in favor of that issue

**Closed by backus** 2017-02-08 19:31 UTC
